### ISSUE TITLE
09.04 피드백

### ISSUE THREAD

**Issue by from97** [hyseoseo/42_FrontEnd#2]
CSS에서는 전체적인 사이즈를 좀 더 실제 페이지와 비슷하게 만드시려면
content 요소들에 좌우 여백을 주시면 좋을 것 같아요
오늘의집 사이트는 좌우 여백이 60px씩 있더라구요
- header-content와 navbar-content, .main-shorcut 등의 요소에 좌우 패딩값이나 마진값을 60px씩 주시고
- main-header도 마찬가지로 마진 값을 오늘의집과 동일하게 맞추시면 좋을 것 같아요 좌우 마진은 60px, padding-top은 30px로 주시면 똑같아져요

```css
.navbar-content {
	padding: 0 60px; 
}

.header-content {
	padding: 10px 60px; /*위아래 패딩값은 그대로 유지*/
}

.main-header {
	padding-top: 30px; 
	margin: 0 60px;
}

.main-shortcut {
	margin: 0px 60px;
}
```
이런식으로요ㅎㅎ

HTML에서는 div 사용을 조금 줄이고 header, nav, footer 등
시맨틱한 태그를 사용해보시는 걸 추천합니다!
